global:
  resolve_timeout: ${ALERT_MANAGER_RESOLVE_TIMEOUT}
  # The smarthost and SMTP sender used for mail notifications.
  smtp_from: ${ALERT_MANAGER_SMTP_FROM}
  smtp_hello: ${ALERT_MANAGER_SMTP_HELLO}
  smtp_smarthost: ${ALERT_MANAGER_SMTP_SMARTHOST}
  smtp_auth_username: ${ALERT_MANAGER_SMTP_AUTH_USERNAME}
  smtp_auth_password: ${ALERT_MANAGER_SMTP_AUTH_PASSWORD}

  # The Slack API URL used for Slack notifications.
  slack_api_url: ${SLACK_API_URL}

# The directory from which notification templates are read.
templates:
  # Default location for alertmanager templates
  - "/etc/prometheus/templates/*.tmpl"

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname]

time_intervals:
  - name: "office-hours"
    time_intervals:
      - weekdays: [monday, tuesday, wednesday, thursday, friday]
        times:
          - start_time: "09:00"
            end_time: "17:00"
        location: ${ALERT_MANAGER_TIMEZONE}

  - name: "after-hours"
    time_intervals:
      - weekdays: [monday, tuesday, wednesday, thursday, friday]
        times:
          - start_time: "17:30"
            end_time: "23:59"
        location: ${ALERT_MANAGER_TIMEZONE}

  - name: "weekends"
    time_intervals:
      - weekdays: [saturday, sunday]
        times:
          - start_time: "00:00"
            end_time: "23:59"
        location: ${ALERT_MANAGER_TIMEZONE}

  - name: "holidays"
    time_intervals:
      - days_of_month: ["1", "25"]
        years: ["2023:2025"]
        months: ["1", "12"]

route:
  receiver: "default-receiver"
  group_wait: 1m
  group_interval: 3m
  repeat_interval: 2h
  group_by: [alertname, severity]
  routes:
    - receiver: office-hours-team
      matchers:
        - severity="warning"
      active_time_intervals:
        - office-hours
      mute_time_intervals:
        - holidays
    - receiver: on-call-team
      matchers:
        - severity=~"critical|warning"
      active_time_intervals:
        - after-hours
        - weekends
        - holidays

receivers:
  - name: slack-receiver
    slack_configs:
      - channel: "${SLACK_CHANNEL_ID}"
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        color: '{{ if eq .Status "firing" }}#FF0000{{ else }}#00FF00{{ end }}'
        actions:
          - text: "${SLACK_ACTION_TEXT}"
            type: button
            url: "{{ .CommonAnnotations.ack_url }}"
  - name: default-receiver
    email_configs:
      - to: ${ALERT_MANAGER_OFFICE_EMAIL_TO}
        send_resolved: true
  - name: office-hours-team
    email_configs:
      - to: ${ALERT_MANAGER_OFFICE_EMAIL_TO}
        send_resolved: true
  - name: on-call-team
    email_configs:
      - to: ${ALERT_MANAGER_OFFICE_EMAIL_TO}
        send_resolved: true
