tally_port_config:
  server_config:
    max_header_bytes: 1048576
    read_header_timeout: 5000000000
    write_timeout: 10000000000
    read_timeout: 10000000000
    idle_timeout: 120000000000
    server_name: "tallyport-server"
    port: ":8080"
    tls_path: "/etc/tallyport/tls"
